#!/bin/bash
# @File: docker_build
# @Editor: WebStorm
# @Author: Austin (From Chengdu.China)
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2023-09-27

